services:
  cloudflare-dns-updater:
    image: ghcr.io/idohomri-io/cloudflare-dns-updater:latest
    container_name: cloudflare-dns-updater
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=
      - DNS_RECORD_0=zone_id:record_id:name
      # - DNS_RECORD_1=zone_id:record_id:name
      - INTERVAL=300